server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/dev_database
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

message: Hello Dev123!